In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_excel(r"C:\Users\ABHISHEK YADAV\Downloads\Pizza_Sales.xlsx")
df

,order_details_id,order_id,pizza_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,21:23:10,16.75,16.75,M,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,2015-12-31,21:23:10,17.95,17.95,L,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,2015-12-31,21:23:10,12.00,12.00,S,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,2015-12-31,22:09:54,20.25,20.25,L,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,2015-12-31,23:02:05,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_details_id   48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_id           48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 4.5+ MB

In [7]:
df.isnull().sum()

order_details_id     0
order_id             0
pizza_id             0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_details_id   48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_id           48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 4.5+ MB

In [10]:
df['pizza_size'].unique()

array(['M', 'L', 'S', 'XL', 'XXL'], dtype=object)

In [11]:

size_map={"S":1,"M":2,"L":3,"XL":4,"XXl":5}
df["pizza_size"]=df["pizza_size"].map(size_map)

In [12]:
df

,order_details_id,order_id,pizza_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13.25,13.25,2.0,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16.00,16.00,2.0,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18.50,18.50,3.0,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20.75,20.75,3.0,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16.00,16.00,2.0,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,21:23:10,16.75,16.75,2.0,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,2015-12-31,21:23:10,17.95,17.95,3.0,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,2015-12-31,21:23:10,12.00,12.00,1.0,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,2015-12-31,22:09:54,20.25,20.25,3.0,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,2015-12-31,23:02:05,12.75,12.75,1.0,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_details_id   48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_id           48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48592 non-null  float64
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(3), object(5)
memory usage: 4.5+ MB

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["pizza_category"].unique()

array(['Classic', 'Veggie', 'Supreme', 'Chicken'], dtype=object)

In [16]:

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["pizza_category"]=encoder.fit_transform(df["pizza_category"])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_details_id   48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_id           48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48592 non-null  float64
 9   pizza_category     48620 non-null  int64
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 4.5+ MB

In [18]:
df

,order_details_id,order_id,pizza_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13.25,13.25,2.0,1,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16.00,16.00,2.0,1,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18.50,18.50,3.0,3,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20.75,20.75,3.0,2,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16.00,16.00,2.0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,21:23:10,16.75,16.75,2.0,0,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza
48616,48617,21348,four_cheese_l,1,2015-12-31,21:23:10,17.95,17.95,3.0,3,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza
48617,48618,21348,napolitana_s,1,2015-12-31,21:23:10,12.00,12.00,1.0,1,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza
48618,48619,21349,mexicana_l,1,2015-12-31,22:09:54,20.25,20.25,3.0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
48619,48620,21350,bbq_ckn_s,1,2015-12-31,23:02:05,12.75,12.75,1.0,0,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza

In [31]:
df["order_time"] = pd.to_datetime(df["order_time"].astype(str))
df["hour"] = df["order_time"].dt.hour

C:\Users\ABHISHEK YADAV\AppData\Local\Temp\ipykernel_15520\3652403136.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["order_time"] = pd.to_datetime(df["order_time"].astype(str))

In [32]:
df

,order_details_id,order_id,pizza_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,hour
0,1,1,hawaiian_m,1,2015-01-01,2026-04-13 11:38:36,13.25,13.25,2.0,1,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,11
1,2,2,classic_dlx_m,1,2015-01-01,2026-04-13 11:57:40,16.00,16.00,2.0,1,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,11
2,3,2,five_cheese_l,1,2015-01-01,2026-04-13 11:57:40,18.50,18.50,3.0,3,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,11
3,4,2,ital_supr_l,1,2015-01-01,2026-04-13 11:57:40,20.75,20.75,3.0,2,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,11
4,5,2,mexicana_m,1,2015-01-01,2026-04-13 11:57:40,16.00,16.00,2.0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,2026-04-13 21:23:10,16.75,16.75,2.0,0,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza,21
48616,48617,21348,four_cheese_l,1,2015-12-31,2026-04-13 21:23:10,17.95,17.95,3.0,3,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza,21
48617,48618,21348,napolitana_s,1,2015-12-31,2026-04-13 21:23:10,12.00,12.00,1.0,1,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza,21
48618,48619,21349,mexicana_l,1,2015-12-31,2026-04-13 22:09:54,20.25,20.25,3.0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,22
48619,48620,21350,bbq_ckn_s,1,2015-12-31,2026-04-13 23:02:05,12.75,12.75,1.0,0,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza,23

In [33]:

df2=df.select_dtypes(["int", "float"])
df2

,order_details_id,order_id,quantity,unit_price,total_price,pizza_size,pizza_category,hour
0,1,1,1,13.25,13.25,2.0,1,11
1,2,2,1,16.00,16.00,2.0,1,11
2,3,2,1,18.50,18.50,3.0,3,11
3,4,2,1,20.75,20.75,3.0,2,11
4,5,2,1,16.00,16.00,2.0,3,11
...,...,...,...,...,...,...,...,...
48615,48616,21348,1,16.75,16.75,2.0,0,21
48616,48617,21348,1,17.95,17.95,3.0,3,21
48617,48618,21348,1,12.00,12.00,1.0,1,21
48618,48619,21349,1,20.25,20.25,3.0,3,22
48619,48620,21350,1,12.75,12.75,1.0,0,23

In [34]:
df2.corr()

,order_details_id,order_id,quantity,unit_price,total_price,pizza_size,pizza_category,hour
order_details_id,1.000000,0.999990,0.003639,-0.003286,-0.000847,-0.004237,-0.006258,0.006392
order_id,0.999990,1.000000,0.003621,-0.003323,-0.000889,-0.004270,-0.006296,0.006419
quantity,0.003639,0.003621,1.000000,0.007142,0.541926,0.012418,-0.012405,-0.058092
unit_price,-0.003286,-0.003323,0.007142,1.000000,0.836087,0.876817,-0.001022,-0.000677
total_price,-0.000847,-0.000889,0.541926,0.836087,1.000000,0.736587,-0.007306,-0.031766
pizza_size,-0.004237,-0.004270,0.012418,0.876817,0.736587,1.000000,0.025627,-0.002118
pizza_category,-0.006258,-0.006296,-0.012405,-0.001022,-0.007306,0.025627,1.000000,0.000413
hour,0.006392,0.006419,-0.058092,-0.000677,-0.031766,-0.002118,0.000413,1.000000

In [35]:
df.isnull().sum()

order_details_id     0
order_id             0
pizza_id             0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
hour                 0
dtype: int64

In [36]:
df['pizza_size']=df['pizza_size'].fillna(df['pizza_size'].mean())

In [37]:

x=df[["quantity","pizza_size","pizza_category","hour"]]
y=df["total_price"]

In [38]:
df

,order_details_id,order_id,pizza_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,hour
0,1,1,hawaiian_m,1,2015-01-01,2026-04-13 11:38:36,13.25,13.25,2.0,1,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,11
1,2,2,classic_dlx_m,1,2015-01-01,2026-04-13 11:57:40,16.00,16.00,2.0,1,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,11
2,3,2,five_cheese_l,1,2015-01-01,2026-04-13 11:57:40,18.50,18.50,3.0,3,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,11
3,4,2,ital_supr_l,1,2015-01-01,2026-04-13 11:57:40,20.75,20.75,3.0,2,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,11
4,5,2,mexicana_m,1,2015-01-01,2026-04-13 11:57:40,16.00,16.00,2.0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,2026-04-13 21:23:10,16.75,16.75,2.0,0,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",The Chicken Alfredo Pizza,21
48616,48617,21348,four_cheese_l,1,2015-12-31,2026-04-13 21:23:10,17.95,17.95,3.0,3,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",The Four Cheese Pizza,21
48617,48618,21348,napolitana_s,1,2015-12-31,2026-04-13 21:23:10,12.00,12.00,1.0,1,"Tomatoes, Anchovies, Green Olives, Red Onions,...",The Napolitana Pizza,21
48618,48619,21349,mexicana_l,1,2015-12-31,2026-04-13 22:09:54,20.25,20.25,3.0,3,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,22
48619,48620,21350,bbq_ckn_s,1,2015-12-31,2026-04-13 23:02:05,12.75,12.75,1.0,0,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza,23

In [39]:
df2=df.select_dtypes(["int", "float"])
df2

,order_details_id,order_id,quantity,unit_price,total_price,pizza_size,pizza_category,hour
0,1,1,1,13.25,13.25,2.0,1,11
1,2,2,1,16.00,16.00,2.0,1,11
2,3,2,1,18.50,18.50,3.0,3,11
3,4,2,1,20.75,20.75,3.0,2,11
4,5,2,1,16.00,16.00,2.0,3,11
...,...,...,...,...,...,...,...,...
48615,48616,21348,1,16.75,16.75,2.0,0,21
48616,48617,21348,1,17.95,17.95,3.0,3,21
48617,48618,21348,1,12.00,12.00,1.0,1,21
48618,48619,21349,1,20.25,20.25,3.0,3,22
48619,48620,21350,1,12.75,12.75,1.0,0,23

In [40]:
df2.corr()

,order_details_id,order_id,quantity,unit_price,total_price,pizza_size,pizza_category,hour
order_details_id,1.000000,0.999990,0.003639,-0.003286,-0.000847,-0.004237,-0.006258,0.006392
order_id,0.999990,1.000000,0.003621,-0.003323,-0.000889,-0.004270,-0.006296,0.006419
quantity,0.003639,0.003621,1.000000,0.007142,0.541926,0.012418,-0.012405,-0.058092
unit_price,-0.003286,-0.003323,0.007142,1.000000,0.836087,0.876817,-0.001022,-0.000677
total_price,-0.000847,-0.000889,0.541926,0.836087,1.000000,0.736587,-0.007306,-0.031766
pizza_size,-0.004237,-0.004270,0.012418,0.876817,0.736587,1.000000,0.025627,-0.002118
pizza_category,-0.006258,-0.006296,-0.012405,-0.001022,-0.007306,0.025627,1.000000,0.000413
hour,0.006392,0.006419,-0.058092,-0.000677,-0.031766,-0.002118,0.000413,1.000000

In [41]:
df.isnull().sum()

order_details_id     0
order_id             0
pizza_id             0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
hour                 0
dtype: int64

In [42]:
x=df[["quantity","pizza_size","pizza_category","hour"]]
y=df["total_price"]

In [43]:
from sklearn import linear_model

In [44]:
regr=linear_model.LinearRegression()
regr.fit(x,y)

LinearRegression()

In [45]:
df['pizza_size'].unique()

array([2.        , 3.        , 1.        , 4.        , 2.11271403])

In [46]:
df['pizza_category'].unique()

array([1, 3, 2, 0])

In [47]:

predicted=regr.predict([[1,5,2,11]])
predicted

C:\Users\ABHISHEK YADAV\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([27.60673788])

In [48]:

print(predicted)

[27.60673788]

In [49]:

predicted2=regr.predict(x)
predicted2

array([16.09594919, 16.09594919, 19.79986548, ..., 12.24273961,
       19.81122039, 12.3246121 ], shape=(48620,))

In [50]:
from sklearn.metrics import r2_score
print(r2_score(y,predicted2))

0.8268362241317218